export interface IUser {
  id: number | null;
  userName: string | null;
  firstName: string | null;
  lastName: string | null;
  nickName: string | null;
  fullName: string | null;
  email: string | null;
  isEmailConfirmed: boolean | null;
  receivedRequestToUpdateEmail: boolean | null;
  receivedRequestToUpdatePassword: boolean | null;
  isActive: boolean | null;
  isSuperUser: boolean | null;
  isAdmin: boolean | null;
  dateCreated: Date | null;
  dateUpdated: Date | null;
  isLoggedIn: boolean | null;
  isLoggingIn: boolean | null;
  isObtainingAssistance: boolean | null;
  isSignedUp: boolean | null;
  isSigningUp: boolean | null;
  isEditing: boolean | null;
}
